### ISSUE TITLE
build_lin deleted most of my home and tried to delete folders from /*

### ISSUE THREAD

**Issue by Alkeryn** [vedderb/vesc_tool#24] opened 2018-09-22 13:40 UTC
Luckily i have backups so i don't think i loosed anything but still
anyway here is the ouptut it made
```
❯ ./build_lin
Info: creating stash file /home/alkeryn/tmp/vesc_tool/.qmake.stash
Project ERROR: Unknown module(s) in QT: quickcontrols2 serialport
make: *** Aucune règle pour fabriquer la cible « clean ». Arrêt.
make: *** Pas de cible spécifiée et aucun makefile n'a été trouvé. Arrêt.
./build_lin: ligne 31 : cd: build/lin: Aucun fichier ou dossier de ce type
  adding: android/ (stored 0%)
  adding: application/ (stored 0%)
  adding: bleuart.cpp (deflated 73%)
  adding: bleuart.h (deflated 59%)
  adding: build_all (deflated 66%)
  adding: build_android (deflated 67%)
  adding: build_cp_fw (deflated 27%)
  adding: build_lin (deflated 66%)
  adding: build_lin_original_only (deflated 23%)
  adding: build_win (deflated 71%)
  adding: build_win_original_only (deflated 28%)
  adding: commands.cpp (deflated 79%)
  adding: commands.h (deflated 64%)
  adding: configparam.cpp (deflated 58%)
  adding: configparam.h (deflated 53%)
  adding: configparams.cpp (deflated 87%)
  adding: configparams.h (deflated 74%)
  adding: datatypes.h (deflated 68%)
  adding: digitalfiltering.cpp (deflated 69%)
  adding: digitalfiltering.h (deflated 52%)
  adding: main.cpp (deflated 62%)
  adding: mainwindow.cpp (deflated 79%)
  adding: mainwindow.h (deflated 69%)
  adding: mainwindow.ui (deflated 89%)
  adding: mobile/ (stored 0%)
  adding: packet.cpp (deflated 64%)
  adding: packet.h (deflated 48%)
  adding: pages/ (stored 0%)
  adding: parametereditor.cpp (deflated 78%)
  adding: parametereditor.h (deflated 59%)
  adding: parametereditor.ui (deflated 91%)
  adding: README.md (deflated 19%)
  adding: res/ (stored 0%)
  adding: res_bronze.qrc (deflated 43%)
  adding: res_free.qrc (deflated 44%)
  adding: res_fw_original.qrc (deflated 74%)
  adding: res_fw.qrc (deflated 85%)
  adding: res_gold.qrc (deflated 43%)
  adding: res_neutral.qrc (deflated 44%)
  adding: res_original.qrc (deflated 44%)
  adding: res_platinum.qrc (deflated 44%)
  adding: res.qrc (deflated 84%)
  adding: res_silver.qrc (deflated 44%)
  adding: setupwizardapp.cpp (deflated 82%)
  adding: setupwizardapp.h (deflated 79%)
  adding: setupwizardmotor.cpp (deflated 80%)
  adding: setupwizardmotor.h (deflated 78%)
  adding: startupwizard.cpp (deflated 76%)
  adding: startupwizard.h (deflated 64%)
  adding: utility.cpp (deflated 65%)
  adding: utility.h (deflated 50%)
  adding: vbytearray.cpp (deflated 73%)
  adding: vbytearray.h (deflated 58%)
  adding: vescinterface.cpp (deflated 76%)
  adding: vescinterface.h (deflated 65%)
  adding: vesc_tool.pro (deflated 67%)
  adding: widgets/ (stored 0%)
rm: impossible de supprimer 'android': est un dossier
rm: impossible de supprimer 'application': est un dossier
rm: impossible de supprimer 'mobile': est un dossier
rm: impossible de supprimer 'pages': est un dossier
rm: impossible de supprimer 'res': est un dossier
rm: impossible de supprimer 'widgets': est un dossier
Usage: qmake [mode] [options] [files]

QMake has two modes, one mode for generating project files based on
some heuristics, and the other for generating makefiles. Normally you
shouldn't need to specify a mode, as makefile generation is the default
mode for qmake, but you may use this to test qmake on an existing project

Mode:
  -project       Put qmake into project file generation mode
                 In this mode qmake interprets files as files to
                 be built,
                 defaults to *; *; *; *.ts; *.xlf; *.qrc
                 Note: The created .pro file probably will 
                 need to be edited. For example add the QT variable to 
                 specify what modules are required.
  -makefile      Put qmake into makefile generation mode (default)
                 In this mode qmake interprets files as project files to
                 be processed, if skipped qmake will try to find a project
                 file in your current working directory

Warnings Options:
  -Wnone         Turn off all warnings; specific ones may be re-enabled by
                 later -W options
  -Wall          Turn on all warnings
  -Wparser       Turn on parser warnings
  -Wlogic        Turn on logic warnings (on by default)
  -Wdeprecated   Turn on deprecation warnings (on by default)

Options:
   * You can place any variable assignment in options and it will be *
   * processed as if it was in [files]. These assignments will be    *
   * processed before [files] by default.                            *
  -o file        Write output to file
  -d             Increase debug level
  -t templ       Overrides TEMPLATE as templ
  -tp prefix     Overrides TEMPLATE so that prefix is prefixed into the value
  -help          This help
  -v             Version information
  -early         All subsequent variable assignments will be
                 parsed right before default_pre.prf
  -before        All subsequent variable assignments will be
                 parsed right before [files] (the default)
  -after         All subsequent variable assignments will be
                 parsed after [files]
  -late          All subsequent variable assignments will be
                 parsed right after default_post.prf
  -norecursive   Don't do a recursive search
  -recursive     Do a recursive search
  -set <prop> <value> Set persistent property
  -unset <prop>  Unset persistent property
  -query <prop>  Query persistent property. Show all if <prop> is empty.
  -qtconf file   Use file instead of looking for qt.conf
  -cache file    Use file as cache           [makefile mode only]
  -spec spec     Use spec as QMAKESPEC       [makefile mode only]
  -nocache       Don't use a cache file      [makefile mode only]
  -nodepend      Don't generate dependencies [makefile mode only]
  -nomoc         Don't generate moc targets  [makefile mode only]
  -nopwd         Don't look for files in pwd [project mode only]
make: *** Aucune règle pour fabriquer la cible « clean ». Arrêt.
make: *** Pas de cible spécifiée et aucun makefile n'a été trouvé. Arrêt.
./build_lin: ligne 41 : cd: build/lin: Aucun fichier ou dossier de ce type
	zip warning: name not matched: This
	zip warning: name not matched: video
	zip warning: name not matched: is
	zip warning: name not matched: blocked.-x4aD_cJAoJE.mp4
updating: App/ (stored 0%)
updating: bin/ (stored 0%)
updating: Cloud/ (stored 0%)
updating: Downloads/ (stored 0%)
updating: Drives/ (stored 0%)
updating: tmp/ (stored 0%)
rm: impossible de supprimer 'App': est un dossier
rm: impossible de supprimer 'bin': est un dossier
rm: impossible de supprimer 'Cloud': est un dossier
rm: impossible de supprimer 'Downloads': est un dossier
rm: impossible de supprimer 'Drives': est un dossier
rm: impossible de supprimer 'This': Aucun fichier ou dossier de ce type
rm: impossible de supprimer 'video': Aucun fichier ou dossier de ce type
rm: impossible de supprimer 'is': Aucun fichier ou dossier de ce type
rm: impossible de supprimer 'blocked.-x4aD_cJAoJE.mp4': Aucun fichier ou dossier de ce type
rm: impossible de supprimer 'tmp': est un dossier
Usage: qmake [mode] [options] [files]

QMake has two modes, one mode for generating project files based on
some heuristics, and the other for generating makefiles. Normally you
shouldn't need to specify a mode, as makefile generation is the default
mode for qmake, but you may use this to test qmake on an existing project

Mode:
  -project       Put qmake into project file generation mode
                 In this mode qmake interprets files as files to
                 be built,
                 defaults to *; *; *; *.ts; *.xlf; *.qrc
                 Note: The created .pro file probably will 
                 need to be edited. For example add the QT variable to 
                 specify what modules are required.
  -makefile      Put qmake into makefile generation mode (default)
                 In this mode qmake interprets files as project files to
                 be processed, if skipped qmake will try to find a project
                 file in your current working directory

Warnings Options:
  -Wnone         Turn off all warnings; specific ones may be re-enabled by
                 later -W options
  -Wall          Turn on all warnings
  -Wparser       Turn on parser warnings
  -Wlogic        Turn on logic warnings (on by default)
  -Wdeprecated   Turn on deprecation warnings (on by default)

Options:
   * You can place any variable assignment in options and it will be *
   * processed as if it was in [files]. These assignments will be    *
   * processed before [files] by default.                            *
  -o file        Write output to file
  -d             Increase debug level
  -t templ       Overrides TEMPLATE as templ
  -tp prefix     Overrides TEMPLATE so that prefix is prefixed into the value
  -help          This help
  -v             Version information
  -early         All subsequent variable assignments will be
                 parsed right before default_pre.prf
  -before        All subsequent variable assignments will be
                 parsed right before [files] (the default)
  -after         All subsequent variable assignments will be
                 parsed after [files]
  -late          All subsequent variable assignments will be
                 parsed right after default_post.prf
  -norecursive   Don't do a recursive search
  -recursive     Do a recursive search
  -set <prop> <value> Set persistent property
  -unset <prop>  Unset persistent property
  -query <prop>  Query persistent property. Show all if <prop> is empty.
  -qtconf file   Use file instead of looking for qt.conf
  -cache file    Use file as cache           [makefile mode only]
  -spec spec     Use spec as QMAKESPEC       [makefile mode only]
  -nocache       Don't use a cache file      [makefile mode only]
  -nodepend      Don't generate dependencies [makefile mode only]
  -nomoc         Don't generate moc targets  [makefile mode only]
  -nopwd         Don't look for files in pwd [project mode only]
make: *** Aucune règle pour fabriquer la cible « clean ». Arrêt.
make: *** Pas de cible spécifiée et aucun makefile n'a été trouvé. Arrêt.
./build_lin: ligne 51 : cd: build/lin: Aucun fichier ou dossier de ce type
zip I/O error: Permission denied
zip error: Could not create output file (vesc_tool_gold_linux.zip)
rm: impossible de supprimer 'bin': Permission non accordée
rm: impossible de supprimer 'boot': est un dossier
rm: impossible de supprimer 'dev': est un dossier
rm: impossible de supprimer 'etc': est un dossier
rm: impossible de supprimer 'home': est un dossier
rm: impossible de supprimer 'lib': Permission non accordée
rm: impossible de supprimer 'lib64': Permission non accordée
rm: impossible de supprimer 'mnt': est un dossier
rm: impossible de supprimer 'opt': est un dossier
rm: impossible de supprimer 'proc': est un dossier
rm: impossible de supprimer 'root': est un dossier
rm: impossible de supprimer 'run': est un dossier
rm: impossible de supprimer 'sbin': Permission non accordée
rm: impossible de supprimer 'srv': est un dossier
rm: impossible de supprimer 'sys': est un dossier
rm: impossible de supprimer 'tmp': est un dossier
rm: impossible de supprimer 'usr': est un dossier
rm: impossible de supprimer 'var': est un dossier
Usage: qmake [mode] [options] [files]

QMake has two modes, one mode for generating project files based on
some heuristics, and the other for generating makefiles. Normally you
shouldn't need to specify a mode, as makefile generation is the default
mode for qmake, but you may use this to test qmake on an existing project

Mode:
  -project       Put qmake into project file generation mode
                 In this mode qmake interprets files as files to
                 be built,
                 defaults to *; *; *; *.ts; *.xlf; *.qrc
                 Note: The created .pro file probably will 
                 need to be edited. For example add the QT variable to 
                 specify what modules are required.
  -makefile      Put qmake into makefile generation mode (default)
                 In this mode qmake interprets files as project files to
                 be processed, if skipped qmake will try to find a project
                 file in your current working directory

Warnings Options:
  -Wnone         Turn off all warnings; specific ones may be re-enabled by
                 later -W options
  -Wall          Turn on all warnings
  -Wparser       Turn on parser warnings
  -Wlogic        Turn on logic warnings (on by default)
  -Wdeprecated   Turn on deprecation warnings (on by default)

Options:
   * You can place any variable assignment in options and it will be *
   * processed as if it was in [files]. These assignments will be    *
   * processed before [files] by default.                            *
  -o file        Write output to file
  -d             Increase debug level
  -t templ       Overrides TEMPLATE as templ
  -tp prefix     Overrides TEMPLATE so that prefix is prefixed into the value
  -help          This help
  -v             Version information
  -early         All subsequent variable assignments will be
                 parsed right before default_pre.prf
  -before        All subsequent variable assignments will be
                 parsed right before [files] (the default)
  -after         All subsequent variable assignments will be
                 parsed after [files]
  -late          All subsequent variable assignments will be
                 parsed right after default_post.prf
  -norecursive   Don't do a recursive search
  -recursive     Do a recursive search
  -set <prop> <value> Set persistent property
  -unset <prop>  Unset persistent property
  -query <prop>  Query persistent property. Show all if <prop> is empty.
  -qtconf file   Use file instead of looking for qt.conf
  -cache file    Use file as cache           [makefile mode only]
  -spec spec     Use spec as QMAKESPEC       [makefile mode only]
  -nocache       Don't use a cache file      [makefile mode only]
  -nodepend      Don't generate dependencies [makefile mode only]
  -nomoc         Don't generate moc targets  [makefile mode only]
  -nopwd         Don't look for files in pwd [project mode only]
make: *** Aucune règle pour fabriquer la cible « clean ». Arrêt.
make: *** Pas de cible spécifiée et aucun makefile n'a été trouvé. Arrêt.
./build_lin: ligne 61 : cd: build/lin: Aucun fichier ou dossier de ce type
zip I/O error: Permission denied
zip error: Could not create output file (vesc_tool_silver_linux.zip)
rm: impossible de supprimer 'bin': Permission non accordée
rm: impossible de supprimer 'boot': est un dossier
rm: impossible de supprimer 'dev': est un dossier
rm: impossible de supprimer 'etc': est un dossier
rm: impossible de supprimer 'home': est un dossier
rm: impossible de supprimer 'lib': Permission non accordée
rm: impossible de supprimer 'lib64': Permission non accordée
rm: impossible de supprimer 'mnt': est un dossier
rm: impossible de supprimer 'opt': est un dossier
rm: impossible de supprimer 'proc': est un dossier
rm: impossible de supprimer 'root': est un dossier
rm: impossible de supprimer 'run': est un dossier
rm: impossible de supprimer 'sbin': Permission non accordée
rm: impossible de supprimer 'srv': est un dossier
rm: impossible de supprimer 'sys': est un dossier
rm: impossible de supprimer 'tmp': est un dossier
rm: impossible de supprimer 'usr': est un dossier
rm: impossible de supprimer 'var': est un dossier
Usage: qmake [mode] [options] [files]

QMake has two modes, one mode for generating project files based on
some heuristics, and the other for generating makefiles. Normally you
shouldn't need to specify a mode, as makefile generation is the default
mode for qmake, but you may use this to test qmake on an existing project

Mode:
  -project       Put qmake into project file generation mode
                 In this mode qmake interprets files as files to
                 be built,
                 defaults to *; *; *; *.ts; *.xlf; *.qrc
                 Note: The created .pro file probably will 
                 need to be edited. For example add the QT variable to 
                 specify what modules are required.
  -makefile      Put qmake into makefile generation mode (default)
                 In this mode qmake interprets files as project files to
                 be processed, if skipped qmake will try to find a project
                 file in your current working directory

Warnings Options:
  -Wnone         Turn off all warnings; specific ones may be re-enabled by
                 later -W options
  -Wall          Turn on all warnings
  -Wparser       Turn on parser warnings
  -Wlogic        Turn on logic warnings (on by default)
  -Wdeprecated   Turn on deprecation warnings (on by default)

Options:
   * You can place any variable assignment in options and it will be *
   * processed as if it was in [files]. These assignments will be    *
   * processed before [files] by default.                            *
  -o file        Write output to file
  -d             Increase debug level
  -t templ       Overrides TEMPLATE as templ
  -tp prefix     Overrides TEMPLATE so that prefix is prefixed into the value
  -help          This help
  -v             Version information
  -early         All subsequent variable assignments will be
                 parsed right before default_pre.prf
  -before        All subsequent variable assignments will be
                 parsed right before [files] (the default)
  -after         All subsequent variable assignments will be
                 parsed after [files]
  -late          All subsequent variable assignments will be
                 parsed right after default_post.prf
  -norecursive   Don't do a recursive search
  -recursive     Do a recursive search
  -set <prop> <value> Set persistent property
  -unset <prop>  Unset persistent property
  -query <prop>  Query persistent property. Show all if <prop> is empty.
  -qtconf file   Use file instead of looking for qt.conf
  -cache file    Use file as cache           [makefile mode only]
  -spec spec     Use spec as QMAKESPEC       [makefile mode only]
  -nocache       Don't use a cache file      [makefile mode only]
  -nodepend      Don't generate dependencies [makefile mode only]
  -nomoc         Don't generate moc targets  [makefile mode only]
  -nopwd         Don't look for files in pwd [project mode only]
make: *** Aucune règle pour fabriquer la cible « clean ». Arrêt.
make: *** Pas de cible spécifiée et aucun makefile n'a été trouvé. Arrêt.
./build_lin: ligne 71 : cd: build/lin: Aucun fichier ou dossier de ce type
zip I/O error: Permission denied
zip error: Could not create output file (vesc_tool_bronze_linux.zip)
rm: impossible de supprimer 'bin': Permission non accordée
rm: impossible de supprimer 'boot': est un dossier
rm: impossible de supprimer 'dev': est un dossier
rm: impossible de supprimer 'etc': est un dossier
rm: impossible de supprimer 'home': est un dossier
rm: impossible de supprimer 'lib': Permission non accordée
rm: impossible de supprimer 'lib64': Permission non accordée
rm: impossible de supprimer 'mnt': est un dossier
rm: impossible de supprimer 'opt': est un dossier
rm: impossible de supprimer 'proc': est un dossier
rm: impossible de supprimer 'root': est un dossier
rm: impossible de supprimer 'run': est un dossier
rm: impossible de supprimer 'sbin': Permission non accordée
rm: impossible de supprimer 'srv': est un dossier
rm: impossible de supprimer 'sys': est un dossier
rm: impossible de supprimer 'tmp': est un dossier
rm: impossible de supprimer 'usr': est un dossier
rm: impossible de supprimer 'var': est un dossier
Usage: qmake [mode] [options] [files]

QMake has two modes, one mode for generating project files based on
some heuristics, and the other for generating makefiles. Normally you
shouldn't need to specify a mode, as makefile generation is the default
mode for qmake, but you may use this to test qmake on an existing project

Mode:
  -project       Put qmake into project file generation mode
                 In this mode qmake interprets files as files to
                 be built,
                 defaults to *; *; *; *.ts; *.xlf; *.qrc
                 Note: The created .pro file probably will 
                 need to be edited. For example add the QT variable to 
                 specify what modules are required.
  -makefile      Put qmake into makefile generation mode (default)
                 In this mode qmake interprets files as project files to
                 be processed, if skipped qmake will try to find a project
                 file in your current working directory

Warnings Options:
  -Wnone         Turn off all warnings; specific ones may be re-enabled by
                 later -W options
  -Wall          Turn on all warnings
  -Wparser       Turn on parser warnings
  -Wlogic        Turn on logic warnings (on by default)
  -Wdeprecated   Turn on deprecation warnings (on by default)

Options:
   * You can place any variable assignment in options and it will be *
   * processed as if it was in [files]. These assignments will be    *
   * processed before [files] by default.                            *
  -o file        Write output to file
  -d             Increase debug level
  -t templ       Overrides TEMPLATE as templ
  -tp prefix     Overrides TEMPLATE so that prefix is prefixed into the value
  -help          This help
  -v             Version information
  -early         All subsequent variable assignments will be
                 parsed right before default_pre.prf
  -before        All subsequent variable assignments will be
                 parsed right before [files] (the default)
  -after         All subsequent variable assignments will be
                 parsed after [files]
  -late          All subsequent variable assignments will be
                 parsed right after default_post.prf
  -norecursive   Don't do a recursive search
  -recursive     Do a recursive search
  -set <prop> <value> Set persistent property
  -unset <prop>  Unset persistent property
  -query <prop>  Query persistent property. Show all if <prop> is empty.
  -qtconf file   Use file instead of looking for qt.conf
  -cache file    Use file as cache           [makefile mode only]
  -spec spec     Use spec as QMAKESPEC       [makefile mode only]
  -nocache       Don't use a cache file      [makefile mode only]
  -nodepend      Don't generate dependencies [makefile mode only]
  -nomoc         Don't generate moc targets  [makefile mode only]
  -nopwd         Don't look for files in pwd [project mode only]
make: *** Aucune règle pour fabriquer la cible « clean ». Arrêt.
make: *** Pas de cible spécifiée et aucun makefile n'a été trouvé. Arrêt.
./build_lin: ligne 81 : cd: build/lin: Aucun fichier ou dossier de ce type
zip I/O error: Permission denied
zip error: Could not create output file (vesc_tool_free_linux.zip)
rm: impossible de supprimer 'bin': Permission non accordée
rm: impossible de supprimer 'boot': est un dossier
rm: impossible de supprimer 'dev': est un dossier
rm: impossible de supprimer 'etc': est un dossier
rm: impossible de supprimer 'home': est un dossier
rm: impossible de supprimer 'lib': Permission non accordée
rm: impossible de supprimer 'lib64': Permission non accordée
rm: impossible de supprimer 'mnt': est un dossier
rm: impossible de supprimer 'opt': est un dossier
rm: impossible de supprimer 'proc': est un dossier
rm: impossible de supprimer 'root': est un dossier
rm: impossible de supprimer 'run': est un dossier
rm: impossible de supprimer 'sbin': Permission non accordée
rm: impossible de supprimer 'srv': est un dossier
rm: impossible de supprimer 'sys': est un dossier
rm: impossible de supprimer 'tmp': est un dossier
rm: impossible de supprimer 'usr': est un dossier
rm: impossible de supprimer 'var': est un dossier
```
Also yeah output is french
Add i run it as root, might have break my system
but how comes a build script delete home files

**Comment by mihlit** [comment] 2018-10-02 18:41
I can confirm this, this is because it tries to 'cd' to directory that would be created during build, but if build fails because of problem with a dependency, 'cd' fails and it continues with other commands that include 'rm'

from build script:

cd build/lin
zip vesc_tool_original_linux.zip `ls | grep -v '\.zip$'`
ls | grep -v '\.zip$' | xargs rm

solution would be to either:
a)
cd build/lin | exit 1

or
b)
cd build/lin
zip vesc_tool_original_linux.zip `ls | grep -v '\.zip$'`
cd ../..
ls build/lin | grep -v '\.zip$' | xargs rm

**Comment by mihlit** [comment] 2018-10-02 18:46
I think this is a duplicate of issue #18

**Comment by vedderb** [comment] 2019-02-20 11:18
I have added set -e to the build script, hopefully that resolves the issue.

**Closed by vedderb** 2019-02-20 11:18 UTC
